costmap:
  ros__parameters:
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: true
    robot_radius: 0.1
    resolution: 0.05
    always_send_full_costmap: true
    track_unknown_space: true
    plugins: ["static_layer"]
    
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_topic: "map"
      map_subscribe_transient_local: true