costmap:
  ros__parameters:
    update_frequency: 1.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: true
    robot_radius: 0.15
    resolution: 0.01
    always_send_full_costmap: true
    track_unknown_space: true
    plugins: ["static_layer, obstacle_layer","inflation_layer"]
    
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_topic: "map"
      map_subscribe_transient_local: true

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: "scan"
      scan:
        topic: "scan"
        data_type: "LaserScan"
        max_obstacle_height: 2.0
        marking: true
        clearing: true
        combination_method: 1
        raytrace_max_range: 3.0
        raytrace_min_range: 0.0
        obstacle_max_range: 2.5
        obstacle_min_range: 0.0

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.25
      cost_scaling_factor: 2.0